### ISSUE TITLE
Consider supporting metric prefixes

### ISSUE THREAD

**Issue by aaronfranke** [ChronoDK/GodotBigNumberClass#1]
I noticed that for declaring large numbers, it quickly switches away from conventional prefixes and instead uses AA, AB, etc. Why not support [metric prefixes](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes)? This would be useful in many contexts.

Also, consider making your code conform to the [GDScript style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html), since it can help users read your code and contribute more easily.

**Comment by ChronoDK** [comment]
Hi Aaron, thank you for commenting. 
As for the AA, AB notation stuff I'm following a convention these kinds of games uses. You can read more about it here: https://gram.gs/gramlog/formatting-big-numbers-aa-notation/
Metric notation would be a cool thing to add though, but it would be limited to some range right? I would also like to add the short and long scale number names: https://googology.wikia.org/wiki/Quattuorquinquagintillion I have made another game that uses these, though that is some years ago.

Can you specify the things from the style guide I'm missing? I'm just writing .gd the way I always have. Would not mind changing it for readability.

**Comment by aaronfranke** [comment]
In particular, spaces after colons, spaces after commas, spaces around `=` and `/` etc, comments starting with a capital letter and ending with a period, two lines between functions, tabs for indentation, and `snake_case` names. You also have stray indentation outside of a function on line 72.

**Comment by ChronoDK** [comment]
I found some time to improve this a bit. I added long name notation like octovigintillion or sextrigintillion, and also metric symbol and metric name notation (falls back to scientific). 

Made some style improvements as well. Not everything I can change though, as I would have to change my game as well.
