### ISSUE TITLE
AA notation starts becoming incorrectly encoded after passing azz

### ISSUE THREAD

**Issue by slzero-X** [ChronoDK/GodotBigNumberClass#11]
normally after azz it should become baa then bab then bac and so on, but however it seems that a small oversight in the encoder makes it fail to replace the second z that is in there even though it does so normally after zz is surpassed. I am currently studying it to fix this error. I'd be baffled if this error was never discovered by anyone using it.

**Comment by ChronoDK** [comment]
Interesting - my own games has never gone that far up, so I never noticed. I don't currently have the time to look into it, but feel free to pull request if you find a fix.

**Comment by ChronoDK** [comment]
I finally fixed this issue :-)

**Comment by slzero-X** [comment]
I missed this message, thank you very much!
