### ISSUE TITLE
isLargerThanOrEqualTo() returns false when supplied with two values of zero

### ISSUE THREAD

**Issue by john-marinelli** [ChronoDK/GodotBigNumberClass#12]
Code that produced the error:

var itemOne = Big.new(0)
var itemTwo = Big.new(0)

print(itemOne.isLargerthanOrEqualTo(itemTwo))

This prints false currently.

**Comment by ChronoDK** [comment]
I am unable to reproduce this. Which version of Godot is this? And is this observed in an export or running from the editor?

**Comment by john-marinelli** [comment]
Version 3.4.4 stable was what was used. It was observed when running from the editor. I'll retry everything as it's been a bit, but I remember being pretty thorough when first testing.

**Comment by john-marinelli** [comment]
Yep, this code still prints false: 
func equal_test():
	var item_one = Big.new(0)
	var item_two = Big.new(0)
	print(item_one.isLargerThanOrEqualTo(item_two))

**Comment by john-marinelli** [comment]
If it helps, this is being tested in a global auto-load script in the _ready() function, and I'm executing from my main game scene in debug mode from the editor.

**Comment by ChronoDK** [comment]
I have fixed this. Better later than never I guess ;-)
