### ISSUE TITLE
min and max functions can return a non-Big object

### ISSUE THREAD

**Issue by Kam1goroshi** [ChronoDK/GodotBigNumberClass#15]
Suppose that n is a float. That means the return type could be float instead of Big and cause unexpected behavior. For example using a Big function on a primitive. I don't know how to fix this because I don't know Godot. For now I will just place results in Big.new(n). The functions are bellow, please update

static func min(m, n):
	if m.isLessThan(n):
		return m
	else:
		return n

static func max(m, n):
	if m.isLargerThan(n):
		return m
	else:
		return n

**Comment by ChronoDK** [comment]
Thanks, I have fixed this.
