### ISSUE TITLE
New Big numbers

### ISSUE THREAD

**Issue by Vadimledyaev** [ChronoDK/GodotBigNumberClass#16]
Hi, today two new big number names were added (Ronna and Quetta)
So now we have ronna (10^27) and quetta (10^30), as well as ronto (10^-27) and quecto (10^-30).

const postfixes_metric_symbol = {"0":"", "1":"K", "2":"M", "3":"G", "4":"T", "5":"P", "6":"E", "7":"Z", "8":"Y", "9":"R", "10":"Q" }
const postfixes_metric_name = {"0":"", "1":"kilo", "2":"mega", "3":"giga", "4":"tera", "5":"peta", "6":"exa", "7":"zetta", "8":"yotta", "9":"ronna", "10":"quetta"}

**Comment by ChronoDK** [comment]
Thanks, I have added them!
