### ISSUE TITLE
it seems minus() plus() not working

### ISSUE THREAD

**Issue by desperis1** [ChronoDK/GodotBigNumberClass#19]
Hi what am i doing wrong ?
multiply, divide works as expected i have issues with plus, minus operations

![Screenshot_20230106_183718](https://user-images.githubusercontent.com/13006332/211067746-4aabb9bd-f84b-4587-b5ef-bf340ba14d4e.png)

**Comment by ChronoDK** [comment]
It seems to be a precision limitation in the toString function. The actual value is fine.

**Comment by desperis1** [comment]
Thank you for your response

**Comment by desperis1** [comment]
Hi Again ! 
Yes value is fine but  is there a way how to print this value ?

**Comment by ChronoDK** [comment]
I'm not sure how to fix it. The string conversion in Godot is very inaccurate.
Anyway, why would you ever print a value like this? You should use AA-notation, scientific-notation or long names. It's done with .toAA(), toScientific() and toLongName()
